spring.application.name=Seguro_Medico

spring.data.mongodb.uri=mongodb://localhost:27017/Seguro_Medicospring.datasource.username=root
spring.datasource.password=dadiaz
spring.jpa.hibernate.ddl-auto=update
